cores <- list(
  amarelo_fechado = "#996100",
  amarelo_escuro = "#E89400",
  amarelo = "#FFCF00",
  amarelo_claro = "#FFE989",
  verde_fechado = "#076907",
  verde_escuro = "#016c59",
  verde_claro = "#1c9099",
  azul_fechado = "#000F69",
  azul_escuro = "#67a9cf",
  azul_Claro = "#bdc9e1",
  roxo_fechado = "#4D005F",
  roxo_escuro = "#750091",
  roxo = "#B000DB",
  roxo_claro = "#E880FF",
  vermelho_fechado = "#7C010E",
  vermelho_escuro = "#BC0215",
  vermelho = "#FF0000",
  vermelho_claro = "#FF9292",
  preto = "#000000",
  cinza_escuro = "#333333",
  cinza = "#838383",
  cinza_claro = "#B3B3B3",
  branco = "#FFFFFF"  
)


tema_base <-  function(base_size = 12){theme(
  line =               element_line(colour = cores$vermelho_escuro, size = .5, linetype = 1,lineend = "butt"),
  rect =               element_rect(size = 0.5, fill = cores$cinza_claro, colour = cores$cinza_claro, linetype = 1),
  text =               element_text(family = "Helvetica", size=10, margin=margin(), face = "plain", colour = cores$cinza_escuro, hjust = 0.5, vjust = 0.5, angle = 0, debug=F, lineheight = 1),
  
  axis.line =          element_line(colour=NA),
  axis.line.x =        element_line(colour=cores$cinza_escuro, size=0.5),
  axis.line.y =        element_line(colour=NA),    
  axis.text =          element_text(size = 8, colour= cores$cinza_escuro),
  axis.text.x =        element_text(size = 10, vjust=0.4, colour=cores$cinza_escuro, face="plain", angle=90, margin = margin(.5,0,0,0)),
  axis.text.y =        element_text(size = 10, colour=cores$cinza_escuro, face="plain", hjust=1),
  axis.ticks =         element_line(colour=NA, size=0.2),
  axis.ticks.y =       element_line(colour=NA, size=0.2),
  axis.title =         element_text(colour = cores$cinza_escuro, margin=margin(t = 10, r = 10, b = 10, l = 10)),
  axis.title.x =       element_text(margin=margin(t = 10, r = 10, b = 10, l = 10)),
  axis.title.y =       element_text(angle = 90, margin=margin(t = 10, r = 10, b = 10, l = 10)),
  axis.ticks.length =  unit(0.3, "lines"),
  
  legend.background =  element_blank(),
  legend.key =         element_blank(),
  legend.key.size =    unit(0.5, "lines"),
  legend.text =        element_text(size=10, colour=cores$cinza_escuro),
  legend.direction =   "horizontal",
  legend.justification = "center",
  legend.position="bottom",
  
  panel.background =   element_rect(fill = cores$cinza_claro, colour = NA),
  panel.border =       element_rect(fill = NA, colour = cores$cinza,  size=0.2),
  panel.grid.major =   element_line(colour = cores$cinza, size = 0.2),
  panel.grid.minor =   element_line(colour = NA, size = 0.2),
  panel.grid.major.x = element_line(colour=cores$cinza, size=0.2),
  panel.grid.minor.x = element_line(colour=NA),
  panel.grid.major.y = element_line(colour=cores$cinza, size=0.2),
  panel.grid.minor.y = element_line(colour=NA),
  
  strip.background =   element_blank(),
  strip.text.x =       element_text(),
  panel.spacing = unit(1, "lines"),
  strip.switch.pad.wrap = unit(3, "lines"),
  strip.switch.pad.grid = unit(3, "lines"),
  
  plot.background =    element_rect(fill = cores$cinza_claro),
  plot.title =         element_text(hjust=0, face="bold.italic", size=14, colour=cores$cinza_escuro, margin=margin(0,0,10,0)),
  plot.subtitle =      element_text(hjust=0, face="bold.italic", size=10, colour=cores$cinza_escuro, margin=margin(0,0,10,0)),
  plot.caption = element_text(size = 10, hjust=0),
  plot.margin =  unit(c(2, 2, 2, 2), "lines"),
  complete = TRUE
)}


tema_base_fundobranco <- function(base_size = 12){
  theme(
    line =               element_line(colour = cores$vermelho_escuro, linewidth = .5, linetype = 1,lineend = "butt"),
    rect =               element_rect(size = 0.5, fill = "white", colour = "white", linetype = 1),
    text =               element_text(size=10, margin=margin(), face = "plain", colour = cores$cinza_escuro, hjust = 0.5, vjust = 0.5, angle = 0, debug=F, lineheight = 1),
    
    axis.line =          element_line(colour=NA),
    axis.line.x =        element_line(colour=cores$cinza_escuro, linewidth=0.5),
    axis.line.y =        element_line(colour=NA),    
    axis.text =          element_text(size = 8, colour= cores$cinza_escuro),
    axis.text.x =        element_text(size = 10, vjust=0.4, colour=cores$cinza_escuro, face="plain", angle=90, margin = margin(.5,0,0,0)),
    axis.text.y =        element_text(size = 10, colour=cores$cinza_escuro, face="plain", hjust=1),
    axis.ticks =         element_line(colour=NA, size=0.2),
    axis.ticks.y =       element_line(colour=NA, size=0.2),
    axis.title =         element_text(colour = cores$cinza_escuro, margin=margin(t = 10, r = 10, b = 10, l = 10)),
    axis.title.x =       element_text(margin=margin(t = 10, r = 10, b = 10, l = 10)),
    axis.title.y =       element_text(angle = 90, margin=margin(t = 10, r = 10, b = 10, l = 10)),
    axis.ticks.length =  unit(0.3, "lines"),
    
    legend.background =  element_blank(),
    legend.key =         element_blank(),
    legend.key.size =    unit(1, "lines"),
    legend.text =        element_text(size=10, colour=cores$cinza_escuro),
    legend.direction =   "horizontal",
    legend.justification = "center", 
    legend.position="bottom",
    
    panel.background =   element_rect(fill = "white", colour = NA),
    panel.border =       element_rect(fill = NA, colour = NA),
    panel.grid.major =   element_line(colour = cores$cinza_claro, size = 0.1),
    panel.grid.minor =   element_line(colour = NA, size = 0.2),
    panel.grid.major.x = element_line(colour=cores$cinza, size=0.2),
    panel.grid.minor.x = element_line(colour=NA),
    panel.grid.major.y = element_line(colour=cores$cinza, size=0.2),
    panel.grid.minor.y = element_line(colour=NA),
    
    strip.background =   element_blank(),
    strip.text.x =       element_text(),
    panel.spacing = unit(1, "lines"),
    strip.switch.pad.wrap = unit(3, "lines"),
    strip.switch.pad.grid = unit(3, "lines"),
    
    plot.background =    element_rect(fill = "white"),
    plot.title =         element_text(hjust=0, face="bold.italic", size=14, colour=cores$cinza_escuro, margin=margin(0,0,10,0)),
    plot.subtitle =      element_text(hjust=0, face="bold.italic", size=10, colour=cores$cinza_escuro, margin=margin(0,0,10,0)),
    plot.caption =       element_text(size = 10, hjust=0),
    # plot.margin =        unit(c(2, 2, 2, 2), "lines"),
    complete =           TRUE
  )}

tema_base_network <- function(base_size = 12, base_family = "Helvetica"){
  theme(
    line =               element_line(colour = cores$azulescuro, size = .5, linetype = 1,lineend = "butt"),
    rect =               element_rect(size = 0.5, fill = "white", colour = "white", linetype = 1),
    text =               element_text(family = "Helvetica", size=10, margin=margin(), face = "plain", colour = cores$cinza_escuro, hjust = 0.5, vjust = 0.5, angle = 0, debug=F, lineheight = 1),
    
    axis.line =          element_line(colour=NA),
    axis.line.x =        element_line(colour=NA, size=0),
    axis.line.y =        element_line(colour=NA),    
    axis.text =          element_text(size = 0, colour= NA),
    axis.text.x =        element_text(size = 0),
    axis.text.y =        element_text(size = 0),
    axis.ticks =         element_line(colour=NA, size=0),
    axis.ticks.y =       element_line(colour=NA, size=0),
    axis.title =         element_text(colour = cores$cinza_escuro, margin=margin(t = 10, r = 10, b = 10, l = 10)),
    axis.title.x =       element_text(size=0),
    axis.title.y =       element_text(size=0),
    axis.ticks.length =  unit(0, "lines"),
    
    legend.background =  element_blank(),
    legend.key =         element_blank(),
    legend.key.size =    unit(1, "lines"),
    legend.text =        element_text(size=10, colour=cores$cinza_escuro),
    legend.direction =   "horizontal",
    legend.justification = "center", 
    legend.position="bottom",
    
    panel.background =   element_rect(fill = "white", colour = NA),
    panel.border =       element_rect(fill = NA, size=0),
    panel.grid.major =   element_line(size=0),
    panel.grid.minor =   element_line(size=0),
    panel.grid.major.x = element_line(size=0),
    panel.grid.minor.x = element_line(size=0),
    panel.grid.major.y = element_line(size=0),
    panel.grid.minor.y = element_line(size=0),
    
    strip.background =   element_blank(),
    strip.text.x =       element_text(),
    panel.spacing = unit(1, "lines"),
    strip.switch.pad.wrap = unit(3, "lines"),
    strip.switch.pad.grid = unit(3, "lines"),
    
    plot.background =    element_rect(fill = "white"),
    plot.title =         element_text(hjust=0, face="bold.italic", size=14, colour=cores$cinza_escuro, margin=margin(0,0,10,0)),
    plot.subtitle =      element_text(hjust=0, face="bold.italic", size=10, colour=cores$cinza_escuro, margin=margin(0,0,10,0)),
    plot.caption =       element_text(size = 10, hjust=0),
    plot.margin =        unit(c(2, 2, 2, 2), "lines"),
    complete =           TRUE
  )}